# Generated by Django 5.0 on 2023-12-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_photos_photo_task_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tasks.task'),
        ),
    ]
