# Generated by Django 5.0 on 2023-12-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_photo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='tasks.task'),
        ),
    ]
